'use strict';

const ESTADO = {
  AGUARDANDO_NOME: 'AGUARDANDO_NOME',
  MENU_SEM_AGENDAMENTO: 'MENU_SEM_AGENDAMENTO',
  MENU_COM_AGENDAMENTO: 'MENU_COM_AGENDAMENTO',
  SELECIONANDO_HORARIO: 'SELECIONANDO_HORARIO',
  DIGITANDO_SERVICO: 'DIGITANDO_SERVICO',
  CONFIRMANDO_AGENDAMENTO: 'CONFIRMANDO_AGENDAMENTO',
  REAGENDANDO_HORARIO: 'REAGENDANDO_HORARIO',
  REAGENDANDO_DESCRICAO: 'REAGENDANDO_DESCRICAO',
  CANCELANDO_MOTIVO: 'CANCELANDO_MOTIVO',
  POS_ACAO: 'POS_ACAO',
  CONVERSA_ENCERRADA: 'CONVERSA_ENCERRADA',
};

module.exports = { ESTADO };
